config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cash_flows#index"
  resources :cash_flows, only: [:index]
  resources :expenses, only: [:new, :create, :show] do
    resources :expense_contents, only: [:destroy, :edit, :update]
  end
  resources :incomes, only: [:new, :create, :show] do
    resources :income_contents, only: [:destroy, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  include ActiveHash::Associations
  has_many :expense_contents

  self.data = [
    {id: 1, name: '食費'}, 
    {id: 2, name: '交通費'}, 
    {id: 3, name: '外食費'}, 
    {id: 4, name: '趣味'}, 
    {id: 5, name: '日用品'}, 
    {id: 6, name: '自動車'}, 
    {id: 7, name: '衣類'}, 
    {id: 8, name: 'スポーツ'},  
    {id: 9, name: '医療費'}, 
    {id: 10, name: '税金'}, 
    {id: 11, name: '光熱費'}, 
    {id: 12, name: '住宅費'}, 
    {id: 13, name: '保険'}, 
    {id: 14, name: '自己投資'}, 
    {id: 15, name: '通信費'}, 
    {id: 16, name: 'その他'},  
  ]
end

app/models/content.rb
class Content < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  belongs_to_active_hash :category
  belongs_to :month
  belongs_to :user, foreign_key: :user_id

end

app/models/expense_category.rb
class ExpenseCategory < ActiveHash::Base
  include ActiveHash::Associations
  has_many :expense_contents

  self.data = [
    {id: 1, name: '食費'}, 
    {id: 2, name: '交通費'}, 
    {id: 3, name: '外食費'}, 
    {id: 4, name: '趣味'}, 
    {id: 5, name: '日用品'}, 
    {id: 6, name: '自動車'}, 
    {id: 7, name: '衣類'}, 
    {id: 8, name: 'スポーツ'},  
    {id: 9, name: '医療費'}, 
    {id: 10, name: '税金'}, 
    {id: 11, name: '光熱費'}, 
    {id: 12, name: '住宅費'}, 
    {id: 13, name: '保険'}, 
    {id: 14, name: '自己投資'}, 
    {id: 15, name: '通信費'}, 
    {id: 16, name: 'その他'},  
  ]
end

app/models/expense_content.rb
class ExpenseContent < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :expense_category
  belongs_to_active_hash :month
  belongs_to :user
end

app/models/income.rb
class Income < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to_active_hash :income_category
  belongs_to :month
  belongs_to :user, foreign_key: :user_id
end

app/models/income_category.rb
class IncomeCategory < ActiveHash::Base
  include ActiveHash::Associations
  has_many :income_contents

  self.data = [
    {id: 1, name: '給与'}, 
    {id: 2, name: '一時所得'}, 
    {id: 3, name: '事業・副業'}, 
    {id: 4, name: '年金'}, 
    {id: 5, name: '配当'}, 
    {id: 6, name: '不動産所得'}, 
    {id: 7, name: 'ポイント'}, 
    {id: 8, name: 'その他収入'},  
  ]
end

app/models/income_content.rb
class IncomeContent < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to_active_hash :income_category
  belongs_to_active_hash :month
  belongs_to :user
end

app/models/month.rb
class Month < ActiveHash::Base
  include ActiveHash::Associations
  has_many :expense_contents
  has_many :income_contents

  self.data = [
    {id: 1, name: '1月'}, 
    {id: 2, name: '2月'}, 
    {id: 3, name: '3月'}, 
    {id: 4, name: '4月'}, 
    {id: 5, name: '5月'}, 
    {id: 6, name: '6月'}, 
    {id: 7, name: '7月'}, 
    {id: 8, name: '8月'},
    {id: 9, name: '9月'},
    {id: 10, name: '10月'}, 
    {id: 11, name: '11月'}, 
    {id: 12, name: '12月'}, 
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :expense_contents
  has_many :income_contents
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  def new
    @month = Month.new
    @income_content = IncomeContent.new
  end

  def create
    @income_content = IncomeContent.create!(income_category_params)
     redirect_to income_path(@income_content.month_id)
  end

  def show
    @months = Month.all
    @month = Month.find(params[:id])

    @user = current_user.id
    
    @income_categories = IncomeCategory.all
    @income_categories_hash = {}
    @income_categories_hash_show = {}
    @income_categories.each do |income_category|
      if income_category.income_contents.where("month_id = #{@month.id}").length >= 1
        #各月の合計金額
        income_category_total_chart = income_category.income_contents.where("month_id = #{@month.id}").where("user_id = #{@user}").collect{ |con| con.money.to_i }.sum
        @income_categories_hash[:"#{income_category.name}"] = [income_category_total_chart, income_category]
      end
    end
    @income = IncomeContent.where("month_id = #{@month.id}").where("user_id = #{@user}").sum(:money).to_i
    @expense = ExpenseContent.where("month_id = #{@month.id}").where("user_id = #{@user}").sum(:money).to_i
    @cash_flow = @income-@expense
  end
  
  private
  def income_category_params
    params.require(:income_content).permit(:income_category_id, :month_id, :content, :money).merge(user_id: current_user.id)
  end
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  def index
    @months = Month.all
    @month = Month.find_by(params[:id])
  end

  def show
    @months = Month.all
    @user = current_user.id
    @month = Month.find(params[:id])
    @categories = Category.all
    @categories_hash = {}
    @categories.each do |category|
      if category.contents.where("month_id = #{@month.id}").length >= 1
        #各月の合計金額
        category_total_chart = category.contents.where("month_id = #{@month.id}").where("user_id = #{@user}").collect{ |con| con.money.to_i }.sum
        @categories_hash[:"#{category.name}"] = [category_total_chart, category]
      end
    end
    @categories_hash_show = {}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cash_flow_helper.rb
module CashFlowHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/edit_helper.rb
module EditHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/moneys_helper.rb
module MoneysHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/new.html.haml
.expense-form
  %h1 支出新規入力
  = form_for(@expense_content, url: contents_path) do |f|
    = f.label :name, "カテゴリー"
    = f.collection_select :category_id, Category.all, :id, :name
    = f.label :month, "月"
    = f.collection_select :month_id, Month.all, :id, :name
    = f.label :content, "内容"
    = f.text_field :content
    = f.label :money, "金額" 
    = f.text_field :money
    = f.submit "登録する"

app/views/contents/show.html.haml
.wrapper
  = render 'shared/expense_sidebar'
  .expenses
    .left-content
      .left-content__title
        %h2.left-content__title__name
        支出の詳細
      .left-content__list
        %table.left-content__list__category
          - @categories_hash.each do |k,v|
            %tr.category{"data-cat-id": v[1].expense_contents.where("month_id = #{@month.id}").where("user_id = #{@user}").length}
              %td.triangle-open
              %td.triangle-close.hidden
              %td.category-name
                = "●#{k}" + ":"
              %td
                = "¥#{v[0]}"  
            
            - v[1].expense_contents.where("month_id = #{@month.id}").where("user_id = #{@user}").each do |con|
              %tr.content-show.hidden
                %td
                %td
                  = "・#{con.content}"+":"
                %td
                  = "¥#{con.money}"
                /%td
                /  =link_to edit_content_path(@expense_content.id), class: "edit_link" do
                /    .edit_btn 編集する
                /%td
                /  =link_to content_path(@content.id),method: :delete, class: "edit_link" do
                /    .destory_btn 削除する

      .left-content__total
        %p.left-content__total__category
          合計:
          = "¥#{ExpenseContent.where("month_id = #{@month.id}").where("user_id = #{@user}").sum(:money).to_i}"
        %p.left-content__total__money
    .chart
      = pie_chart @categories_hash, id: "total-chart", width: "500px", height: "400px"
    

    
:css
  .category-name {
    width: 200px;
  }
  .triangle-open {
    width: 0;
    height: 0;
    border-left: 15px solid transparent;
    border-right: 15px solid transparent;
    border-top: 10px solid black;
  }
  .triangle-close{
    width: 0;
    height: 0;
    border-left: 15px solid transparent;
    border-right: 15px solid transparent;
    border-bottom: 10px solid black;
    
  }
  .hidden {
    display: none;
  }

app/views/incomes/new.html.haml
.new-form
  %h1 収入新規入力
  = form_for(@income_content, url: incomes_path(@income_content.id)) do |f|
    = f.label :name, "カテゴリー"
    = f.collection_select :income_category_id, IncomeCategory.all, :id, :name
    = f.label :month, "月"
    = f.collection_select :month_id, Month.all, :id, :name
    = f.label :content, "内容"
    = f.text_field :content
    = f.label :money, "金額" 
    = f.text_field :money
    = f.submit "登録する"

app/views/incomes/show.html.haml
.wrapper
  = render 'shared/income_sidebar'
  .contents
    .left-content
      .left-content__title
        %h2.left-content__title__name
        収入の詳細
      .left-content__list
        %table.left-content__list__category
          - @income_categories_hash.each do |k,v|
            %tr.category{"data-cat-id": v[1].income_contents.where("month_id = #{@month.id}").where("user_id = #{@user}").length}
              %td.triangle-open
                ▶︎
              %td.triangle-close.hidden
                ▼
              %td.category-name
                = "●#{k}" + ":"
              %td.category-money
                = "¥#{v[0].to_s(:delimited)}"  
            
            - v[1].income_contents.where("month_id = #{@month.id}").where("user_id = #{@user}").each do |con|
              %tr.content-show.hidden
                %td
                %td
                  = "・#{con.content}"+":"
                %td
                  = "¥#{con.money.to_i.to_s(:delimited)}"
                %td
                  =link_to edit_income_income_content_path(@month.id, con.id), class: "edit_link" do
                    .edit_btn 編集する
                %td
                  =link_to income_income_content_path(@month.id, con.id),method: :delete, class: "destroy_link" do
                    .destory_btn 削除する
      
      .left-content__total
        %p.left-content__total__category
          合計:
          = "¥#{IncomeContent.where("month_id = #{@month.id}").where("user_id = #{@user}").sum(:money).to_i.to_s(:delimited)}"
    .chart
      = pie_chart @income_categories_hash, id: "total-chart", width: "500px", height: "400px"
    

    
:css
  .triangle-open {
    cursor: pointer;
  }
  .triangle-close {
    cursor: pointer;
  }
  .category-name {
    width: 200px;
  }
  .hidden {
    display: none;
  }