config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cash_flows#index"
  resources :cash_flows, only: [:index]
  resources :expenses, only: [:new, :create, :show] do
    resources :expense_contents, only: [:destroy, :edit, :update]
  end
  resources :incomes, only: [:new, :create, :show] do
    resources :income_contents, only: [:destroy, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  include ActiveHash::Associations
  has_many :expense_contents

  self.data = [
    {id: 1, name: '食費'}, 
    {id: 2, name: '交通費'}, 
    {id: 3, name: '外食費'}, 
    {id: 4, name: '趣味'}, 
    {id: 5, name: '日用品'}, 
    {id: 6, name: '自動車'}, 
    {id: 7, name: '衣類'}, 
    {id: 8, name: 'スポーツ'},  
    {id: 9, name: '医療費'}, 
    {id: 10, name: '税金'}, 
    {id: 11, name: '光熱費'}, 
    {id: 12, name: '住宅費'}, 
    {id: 13, name: '保険'}, 
    {id: 14, name: '自己投資'}, 
    {id: 15, name: '通信費'}, 
    {id: 16, name: 'その他'},  
  ]
end

app/models/content.rb
class Content < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  belongs_to_active_hash :category
  belongs_to :month
  belongs_to :user, foreign_key: :user_id

end

app/models/expense_category.rb
class ExpenseCategory < ActiveHash::Base
  include ActiveHash::Associations
  has_many :expense_contents

  self.data = [
    {id: 1, name: '食費'}, 
    {id: 2, name: '交通費'}, 
    {id: 3, name: '外食費'}, 
    {id: 4, name: '趣味'}, 
    {id: 5, name: '日用品'}, 
    {id: 6, name: '自動車'}, 
    {id: 7, name: '衣類'}, 
    {id: 8, name: 'スポーツ'},  
    {id: 9, name: '医療費'}, 
    {id: 10, name: '税金'}, 
    {id: 11, name: '光熱費'}, 
    {id: 12, name: '住宅費'}, 
    {id: 13, name: '保険'}, 
    {id: 14, name: '自己投資'}, 
    {id: 15, name: '通信費'}, 
    {id: 16, name: 'その他'},  
  ]
end

app/models/expense_content.rb
class ExpenseContent < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :expense_category
  belongs_to_active_hash :month
  belongs_to :user
end

app/models/income.rb
class Income < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to_active_hash :income_category
  belongs_to :month
  belongs_to :user, foreign_key: :user_id
end

app/models/income_category.rb
class IncomeCategory < ActiveHash::Base
  include ActiveHash::Associations
  has_many :income_contents

  self.data = [
    {id: 1, name: '給与'}, 
    {id: 2, name: '一時所得'}, 
    {id: 3, name: '事業・副業'}, 
    {id: 4, name: '年金'}, 
    {id: 5, name: '配当'}, 
    {id: 6, name: '不動産所得'}, 
    {id: 7, name: 'ポイント'}, 
    {id: 8, name: 'その他収入'},  
  ]
end

app/models/income_content.rb
class IncomeContent < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to_active_hash :income_category
  belongs_to_active_hash :month
  belongs_to :user
end

app/models/month.rb
class Month < ActiveHash::Base
  include ActiveHash::Associations
  has_many :expense_contents
  has_many :income_contents

  self.data = [
    {id: 1, name: '1月'}, 
    {id: 2, name: '2月'}, 
    {id: 3, name: '3月'}, 
    {id: 4, name: '4月'}, 
    {id: 5, name: '5月'}, 
    {id: 6, name: '6月'}, 
    {id: 7, name: '7月'}, 
    {id: 8, name: '8月'},
    {id: 9, name: '9月'},
    {id: 10, name: '10月'}, 
    {id: 11, name: '11月'}, 
    {id: 12, name: '12月'}, 
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :expense_contents
  has_many :income_contents
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cash_flow_helper.rb
module CashFlowHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/edit_helper.rb
module EditHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/moneys_helper.rb
module MoneysHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Kakeibo
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    
    = yield

app/views/shared/_expense_sidebar.html.haml
.header
  =link_to root_path, class: "header__title__link" do
    %h1.header__title kakeibo
  %h1.header__manth 
    = "#{@month.name}の支出"
  %h2.header__user_name
    = "user : #{current_user.name}"
  %h3.header__cash_flow  
    %span 収入 ー 支出 = 
    収支
  %h3.header__cash_flow-money
    %span= "¥#{@income.to_i.to_s(:delimited)} - ¥#{@expense.to_i.to_s(:delimited)} = "
    = "¥#{@cash_flow.to_i.to_s(:delimited)}"
  =link_to income_path, class: "header__change" do
    .header__change__btn 収入ページへ
  =link_to destroy_user_session_path, class: "header__logout", method: :delete do
    .header__logout__btn ログアウト
  =link_to new_expense_path, class: "header__new" do
    .header__new__btn 金額入力へ
.side-contents
  - @months.each do |month|
    = link_to expense_path(month.id),class: "side-content__link"  do
      %ul.side-content
        %li.side-content__month
          = month.name
        %li.side-content__money
          = "¥#{ExpenseContent.where("month_id = #{month.id}").where("user_id = #{@user}").sum(:money).to_i.to_s(:delimited)}"

:css
  .header {
    background-color: #CC0000;
  }
  span {
    opacity: 0.7;
  }

app/views/shared/_header.html.haml
- if user_signed_in? 
  %h1.header__manth 
    = "ようこそ#{current_user.name}さん！見たい月を選んで下さい。"
  =link_to destroy_user_session_path, class: "header__logout", method: :delete do
    .header__logout__btn ログアウト
  =link_to income_path(1), class: "header__income" do
    .header__logout__btn 収入ページへ
  =link_to content_path(1), class: "header__expense" do
    .header__logout__btn 支出ページへ
- else
  =link_to new_user_registration_path, class: "header__registration" do
    .header__registration__btn 新規登録
  =link_to new_user_session_path, class: "header__login" do
    .header__login__btn ログイン

app/views/shared/_income_sidebar.html.haml
.header
  =link_to root_path, class: "header__title__link" do
    %h1.header__title kakeibo
  %h1.header__manth 
    = "#{@month.name}の収入"
  %h2.header__user_name
    = "user : #{current_user.name}"
  %h3.header__cash_flow  
    %span 収入 ー 支出 = 
    収支
  %h3.header__cash_flow-money
    %span= "¥#{@income.to_s(:delimited)} - ¥#{@expense.to_s(:delimited)} = "
    = "¥#{@cash_flow.to_i.to_s(:delimited)}"
  =link_to expense_path, class: "header__change" do
    .header__change__btn 支出ページへ
  =link_to destroy_user_session_path, class: "header__logout", method: :delete do
    .header__logout__btn ログアウト
  =link_to new_income_path, class: "header__new" do
    .header__new__btn 金額入力へ
.side-contents
  - @months.each do |month|
    = link_to income_path(month.id),class: "side-content__link"  do
      %ul.side-content
        %li.side-content__month
          = month.name
        %li.side-content__money
          = "¥#{IncomeContent.where("month_id = #{month.id}").where("user_id = #{@user}").sum(:money).to_i.to_s(:delimited)}"

:css
  .header {
    background-color: #000088;
  }
  span {
    opacity: 0.7;
  }